name=ACNode
version=1.1.0
author=dirkx
maintainer=dirkx
sentence=Access Control node for the Makerspace in Leiden,NL
paragraph=LAccess Control node for the Makerspace in Leiden,NL
category=Communication
url=https://github.com/dirkx/AccesSystem.git
architectures=esp32
depends=PubSubClient,TLog,AccelStepper Adafruit MCP23017 Arduino Library,Adafruit BusIO,Adafruit AW9523,ArduinoJson,Adafruit GFX Library,Adafruit SH110X,ESP Async WebServer,Async TCP,MFRC522-spi-i2c-uart-async,Adafruit SSD1306,PN532,PN532_I2C,Adafruit PN532,ButtonDebounce
