//
// main.cpp
// Main file
// ----------------------------------
// Developed with embedXcode+
// http://embedXcode.weebly.com
//
// Project 		ACNodePlus
//
// Created by 	Dirk-Willem van Gulik (LAN), 26/01/2018 23:01
//              Dirk-Willem van Gulik
//
// Copyright 	© Dirk-Willem van Gulik (LAN), 2018
// Licence 		Apache Software License 2.0
//
// See 			ACNodePlus.ino and ReadMe.txt for references
//
// ----------------------------------
// DO NOT EDIT THIS FILE.
// THE SKETCH IS IN ACNodePlus.ino
// ----------------------------------
//
// Last update: Jun 30, 2017 release 7.5.0

// IDE selection
#if defined(EMBEDXCODE)

// Core library and main()
// Minimal proxy main() to be updated at build
#include "Arduino.h"

int main(void)
{
    setup();

    for (;;)
    {
        loop();
    }

    return 0;
}

// Sketch
#include "ACNodePlus.ino"


#endif                                                                          // end embedXcode

